server.host: 0.0.0.0

elasticsearch.hosts: ["${ELASTICSEARCH_HOSTS}"]
elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"

xpack.security.encryptionKey: ${XPACK_SECURITY_ENCRYPTIONKEY}
xpack.encryptedSavedObjects.encryptionKey: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
xpack.reporting.encryptionKey: ${XPACK_REPORTING_ENCRYPTIONKEY}

xpack.screenshotting.browser.chromium.disableSandbox: true # needed for aarch

xpack.reporting.roles.enabled: FALSE
xpack.reporting.csv.scroll.duration: 2m
xpack.reporting.csv.maxSizeBytes: 999999999999

logging:
  loggers:
    - name: plugins.screenshotting
      level: debug
    - name: plugins.reporting
      level: debug
